"""Add relationships

Revision ID: 788495dcd8fa
Revises: 3cc0dc0334fe
Create Date: 2025-11-25 18:15:06.038678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788495dcd8fa'
down_revision: Union[str, Sequence[str], None] = '3cc0dc0334fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canteens', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('menu_items', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('profile_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_data')
    op.drop_column('menu_items', 'extra_data')
    op.drop_column('canteens', 'settings')
    # ### end Alembic commands ###
